# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('address', models.TextField(verbose_name='地址')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
