# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190613_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
    ]
