# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, verbose_name='课程名')),
                ('type', models.CharField(choices=[(1, 'Python训练营'), (2, 'Python自动化'), (3, 'Go实战班'), (4, 'Docker+K8s')], max_length=1, verbose_name='课程类型')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课表表',
                'verbose_name_plural': '课表表',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, verbose_name='课程名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.CharField(choices=[(1, '男'), (2, '女')], max_length=1, verbose_name='性别')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('username', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False, verbose_name='用户名')),
                ('introduction', models.TextField(default='这个人很懒，什么都没留下.', verbose_name='简介')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '讲师信息表',
                'verbose_name_plural': '讲师信息表',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='TeacherAssistant',
            fields=[
                ('username', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False, verbose_name='用户名')),
                ('love', models.TextField(blank=True, null=True, verbose_name='爱好')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '助教信息表',
                'verbose_name_plural': '助教信息表',
                'db_table': 'teacher_assistant',
            },
        ),
    ]
