# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='introduction',
            new_name='intro',
        ),
    ]
