# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190620_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.IntegerField(choices=[(1, 'Python训练营'), (2, 'Python自动化'), (3, 'Go实战班'), (4, 'Docker+K8s')], max_length=1, verbose_name='课程类型'),
        ),
    ]
