# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import show.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='背景名')),
                ('img_upload', models.ImageField(storage=show.storage.BackgroundStorage(), upload_to='background', verbose_name='图片上传路径')),
            ],
            options={
                'verbose_name': '背景图片',
                'verbose_name_plural': '背景图片',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_upload', models.ImageField(storage=show.storage.ImageStorage(), upload_to='img/%Y/%m/%d', verbose_name='图片上传路径')),
                ('img_title', models.CharField(max_length=100, unique=True, verbose_name='图片标题')),
                ('img_context', models.TextField(blank=True, max_length=100, null=True, verbose_name='图片介绍')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('display', models.BooleanField(default=True, verbose_name='显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='图片发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='图片更新时间')),
                ('author', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
            },
        ),
        migrations.CreateModel(
            name='PhotoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='相册名')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='img_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='show.PhotoGroup'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img_tags',
            field=models.ManyToManyField(blank=True, to='show.Tag'),
        ),
    ]
